### ISSUE TITLE
Problem with templates

### ISSUE THREAD

**Issue by danka74** [openEHR/gdl-tools#6]
I'm having problems selecting elements from a CLUSTER archetype in a template (see attachment, rename to .oet). All archetypes referenced in the template are imported before trying to select an element. The result is:
`Internal error : Parent node not found at /data[at0001]/events[at0002]/events[at0002 and name/value='Any event']/state[at0.91]/items[at0.92], computed parentPath: /data[at0001]/events[at0002]/events[at0002 and name/value='Any event']/state[at0.91]`

Using Oracle Java 1.7.0_80 on Linux 64 bit

Template file (renamed as .txt to allow upload)
[bg_ao.txt](https://github.com/openEHR/gdl-tools/files/242042/bg_ao.txt)

**Comment by icorbal** [comment]
It seems like the template flattener does not like like the name/value in the event node. The quickest fix for now would be editing the template, instead of 

<Items xsi:type="CLUSTER" archetype_id="openEHR-EHR-CLUSTER.ambient_oxygen.v1" concept_name="Ambient oxygen" path="/data[at0001]/events[at0002 and name/value='Any event']/state[at0.91]/items[at0.92]" />

try using

 <Items xsi:type="CLUSTER" archetype_id="openEHR-EHR-CLUSTER.ambient_oxygen.v1" concept_name="Ambient oxygen" path="/data[at0001]/events[at0002]/state[at0.91]/items[at0.92]" />

**Comment by danka74** [comment]
Thanks, it works now!
